gerenciador_tarefas/app/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from .views.tarefa_views import *
from .views.usuario_views import *
from .views.testes_views import *
from .views.musica_views import*
from .views.professor_views import*


from django.conf.urls import url





urlpatterns = [
    path('listar_tarefas/', views.tarefa_views.listar_tarefas),
    path('cadastrar_tarefa/', views.tarefa_views.cadastrar_tarefa),
    path('listar_tarefas/editar_tarefa/<int:id>',views.tarefa_views.editar_tarefa , name='editar'),
    path('listar_tarefas/remover_tarefa/<int:id>',views.tarefa_views.remover_tarefa, name= 'remover '),
    path('teste', views.tarefa_views.teste),
    path('ego',views.tarefa_views.ego),
    path('ego2',views.testes_views.ego2),    
    path('cadastrar_usuario/', views.usuario_views.cadastrar_usuario, name ='usuario_Cadastrar'),
    path('logar_usuario/', views.usuario_views.logar_usuario , name= 'logar'),
    path('logout/', views.usuario_views.deslogar , name= 'deslogar'),
    path('cadastrar_perguntas/', views.testes_views.adicionar_pergunta),
    path('listar_perguntas/',views.testes_views.listar_perguntas),
    path('cadastrar_professor/',views.professor_views.cadastrar_professor),
    url(r'^musics/', views.musica_views.MusicList.as_view(), name='music-list'),
    url(r'^listar_alunos/', views.tarefa_views.ListAlunos.as_view(),name='alunos'),
    url(r'^tarefas/',views.tarefa_views.ListTarefas.as_view(), name= 'tarefas'),

]

gerenciador_tarefas/gerenciador_tarefas/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('clientes.urls'))
]

gerenciador_tarefas/app/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Tarefa(models.Model):
    PRIORIDADE_CHOICES = [
        ("A", "ALTA"),
        ("N", "NORMAL"),
        ("B", "BAIXA"),
    ]
    titulo = models.CharField('titulo',max_length=30,null=False,blank=False)
    descricao = models.TextField('descrica',max_length=130,null=False,blank=False)
    data_expiracao = models.DateField('data',null=False,blank=False)
    prioridade = models.CharField('prioridade', max_length = 1,choices = PRIORIDADE_CHOICES ,null=False,blank=False)
    usuario = models.ForeignKey(User,null=True, on_delete=models.CASCADE)



class Professor(models.Model):

    nome = models.CharField('nome',max_length=60,null=False,blank=False)
    senha = models.IntegerField('senha',null=False,blank=False)
    confirmarSenha = models.IntegerField('confirmarSenha',null=False,blank=False)

class Testes(models.Model):

    PRIORIDADE_CHOICES = [
        ("1", "Estados-do-Ego"),
        ("2", "Personalidade"),
    ]
    nome = models.IntegerField('nome',choices = PRIORIDADE_CHOICES ,null=False,blank=False)
    # aluno= models.ForeignKey("Aluno", on_delete=models.CASCADE, related_name='Testes', null=False)

class Resposta(models.Model):

    PRIORIDADE_CHOICES = [
        ("0", "Muito-Raramente"),
        ("1", "As-Vezes"),
        ("2", "Frequentemente"),
        ("3", "Sempre"),
    ]
    Resposta = models.IntegerField('resposta',choices = PRIORIDADE_CHOICES ,null=False,blank=False)

    # questionario = models.ManyToManyField(Questionario)

class Questionario(models.Model):
    
    PRIORIDADE_CHOICES = [
        ("1", "Ego"),
        ("2", "Personalidade"),
    ]

    tipo = models.CharField('tipo', max_length = 1,choices = PRIORIDADE_CHOICES ,null=False,blank=False)
    # pergunta = models.CharField('pergunta',max_length=100,null=False,blank=True)
    # usuario = models.ForeignKey(User,null=True, on_delete=models.CASCADE)
    # aluno = models.ForeignKey("Aluno",on_delete=models.CASCADE, related_name='questionario')
    respostas = models.OneToOneField(Resposta, on_delete=models.SET_NULL, null= True)
   

class Disciplina(models.Model):

    nome = models.IntegerField('nome',null=False,blank=False)
    professor = models.ManyToManyField(Professor)



class ComplementoUser(models.Model):
    
    usuario = models.OneToOneField(User,null=True, on_delete=models.CASCADE,related_name='complementoUser')


class Music(models.Model):

    class Meta:

        db_table = 'music'

    title = models.CharField(max_length=200)
    seconds = models.IntegerField()

    def __str__(self):
        return self.title

gerenciador_tarefas/app/views/tarefa_views.py
from django.shortcuts import render,redirect,HttpResponse
from ..forms import TarefaForm
from django.contrib.auth.decorators import login_required
from ..entidades.tarefa import tarefa
from ..services import tarefa_service
# from ..services import aluno_service
# from ..models import Aluno
from ..models import Tarefa
from rest_framework import generics
from ..serializers import AlunoSerializer
from ..serializers import TarefaSerializer

# Create your views here.

class ListAlunos(generics.ListCreateAPIView):

    # queryset = Aluno.objects.all()
    serializer_class = AlunoSerializer

class ListTarefas(generics.ListCreateAPIView):

    queryset = Tarefa.objects.all()
    serializer_class =TarefaSerializer


def home(request):
    return render(request,'tarefas/form_tarefa.html')

def teste(request):
    return render(request,'testes/FormEstEgo.html')

def ego(request):
    aluno = aluno_service.id_aluno(request.user)
    return render(request,'testes/estados_dos_egos.html',{"aluno":aluno})

@login_required()
def listar_tarefas(request):

    tarefas = tarefa_service.listar_tarefas(request.user)

    # alunos = Aluno.objects.all()
    

    context = {
        # 'alunos': alunos,
        'tarefas': tarefas,
    }

    return render(request,'tarefas/listar_tarefas.html',context)


@login_required()
def cadastrar_tarefa(request):

    form_tarefa = TarefaForm()
    if request.method == "POST":
        form_tarefa = TarefaForm(request.POST)
        if form_tarefa.is_valid():
            titulo = form_tarefa.cleaned_data["titulo"]
            descricao = form_tarefa.cleaned_data["descricao"]
            data_expiracao = form_tarefa.cleaned_data["data_expiracao"]
            prioridade = form_tarefa.cleaned_data["prioridade"]
            tarefa_nova = tarefa(titulo=titulo,descricao=descricao,data_expiracao=data_expiracao,
            prioridade=prioridade,usuario=request.user)
            tarefa_service.cadastrar_tarefa(tarefa_nova)
            return redirect('/listar_tarefas')
        else:
            form_tarefa = TarefaForm()


    return render(request,'tarefas/form_tarefa.html', {"form_tarefa":form_tarefa})

@login_required()

def editar_tarefa(request,id):
    tarefa_bd = tarefa_service.listar_tarefa_id(id) 
    if tarefa_bd != request.user:
        return HttpResponse("Não permitido")  
    form_tarefa = TarefaForm(request.POST or None ,instance=tarefa_bd)
    if form_tarefa.is_valid():
         titulo = form_tarefa.cleaned_data["titulo"]
         descricao = form_tarefa.cleaned_data["descricao"]
         data_expiracao = form_tarefa.cleaned_data["data_expiracao"]
         prioridade = form_tarefa.cleaned_data["prioridade"]
         tarefa_nova = tarefa(titulo=titulo,descricao=descricao,data_expiracao=data_expiracao,
         prioridade=prioridade,usuario = request.user)
         tarefa_service.editar_tarefa(tarefa_bd,tarefa_nova)
    return render(request,'tarefas/form_tarefa.html',{"form_tarefa":form_tarefa})

@login_required()
def remover_tarefa(request,id):

    tarefa_bd = tarefa_service.listar_tarefa_id(id)
    if tarefa_bd != request.user:
        return HttpResponse("Não permitido")  
    if request.method == "POST":
        tarefa_service.remover_tarefa(tarefa_bd)
        return redirect('/listar_tarefas')
    return render(request,'tarefas/confirma_exclusao.html',{"tarefa":tarefa_bd})
    

gerenciador_tarefas/app/templates/tarefas/confirma_exclusao.html
{% extends 'base.html'%}
{% block conteudo %}


<div class="card mb-3">
    <div class="card-header">
        Tem certeza que deseja excluir?
    </div>
    <div class="card-body">
        <h5 class="card-title">{{ tarefa.titulo}}</h5>
        <p class="card-text">{{tarefa.descricao}}</p>
        <hr>
        <form method="POST">
            {% csrf_token %}
            <button class="btn btn-danger" type="submit">Remover</button>

        </form>
    </div>


</div>


{% endblock conteudo %}

gerenciador_tarefas/app/templates/tarefas/form_tarefa.html
{% extends 'base.html'%}
{% block conteudo %}

<h2>Cadastrar Tarefa</h2>
<div class="container">

<form method="POST">
    
    {% csrf_token %}

    <div class="form_group">
        {{form_tarefa.titulo.errors}}
        <label>Titulo:</label>
        {{form_tarefa.titulo}}
    </div>
    <div class="form_group">
        
        {{form_tarefa.descricao.errors}}

        <label>Descricao:</label>
        <div>
        {{form_tarefa.descricao}}
        </div>
    </div>
    <div class="form_group">
        {{form_tarefa.data_expiracao.errors}}

        <label>Data: Formato _/ /_</label>
        {{form_tarefa.data_expiracao}}
    </div>
    <div class="form_group">
        {{form_tarefa.prioridade.errors}}

        <label>Prioridade:</label>
        {{form_tarefa.prioridade}}
    </div>
    <div class = "form_group">
            <input type = "submit" value = "salvar">
    </div>
            
</form>
</div>
{% endblock conteudo%}

gerenciador_tarefas/app/templates/tarefas/listar_tarefas.html
{% extends 'base.html'%}
{% block conteudo %}
{% csrf_token %}

<h1>Listagem de Tarefas</h1>

{% for x in tarefas %}

<div class="card mb-3">
    <div class ="card-header">
            {{x.get_prioridade_display}}
    </div>
    <div class = "card-body">
        <h5 class="card-title">{{x.titulo}}</h5>
        <p class="card-text">{{x.descricao}}</p>
        <p class="card-text">{{x.data_expiracao}}</p>
        <a href="editar_tarefa/{{x.id}}">Alterar</a>
        <a href="remover_tarefa/{{x.usuario_id}}">Remover</a>

        <!-- <div>
            <select>
                {% for x in alunos %}
                <option value="{{  x.pk }}">{{ x.nome }}</option>
                {% endfor %}
            </select>
                {{ request.user.username }}
            </div> -->
       
    </div>

</div>

{% endfor%}

<a href="/cadastrar_tarefa"><input type = "button" class="btn btn-primary mb-3" value="Cadastrar Tarefa"></a>


{% endblock conteudo%}